myproject/Mine/urls.py
from django.conf.urls import url
from . import views
app_name = 'Mine'
urlpatterns = [
    url(r'^Mine/$', views.IndexView.as_view(), name='home'),
    url(r'^Algorithm/$', views.AlgorithmListView.as_view(), name='Algorithm'),
]

myproject/myproject/urls.py
from django.contrib import admin
from django.conf.urls import url,include
from mysite.feeds import AllPostsRssFeed
# from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'',include('mysite.urls')),
    url(r'',include('comments.urls')),
    url(r'',include('Mine.urls')),
    url(r'^search/', include('haystack.urls')),
    url(r'^all/rss/$', AllPostsRssFeed(), name='rss'),
    # url(r'^$',views.index,name='index')
]

myproject/mysite/urls.py
from django.conf.urls import url

from . import views

app_name = 'mysite'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^post/(?P<pk>[0-9]+)/$', views.PostDetailView.as_view(), name='detail'),
    url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.ArchivesView.as_view(), name='archives'),
    url(r'^category/(?P<pk>[0-9]+)/$', views.CategoryView.as_view(), name='category'),
    url(r'^tag/(?P<pk>[0-9]+)/$', views.TagView.as_view(), name='tag'),
]

myproject/mysite/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

from django.urls import reverse

from django.contrib.auth.models import User

import markdown
from django.utils.html import strip_tags


# Create your models here.
class Test(models.Model):
    name = models.CharField(max_length=20)
    age = models.CharField(max_length=10, default='30')


class Test2(models.Model):
    testName = models.CharField(max_length=20, default='2017')


class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Post(models.Model):
    ishide = models.BooleanField(default=False)
    title = models.CharField(max_length=100)

    def __str__(self):
        return self.title

    body = models.TextField()

    created_time = models.DateTimeField()
    modified_time = models.DateTimeField()
    excerpt = models.CharField(max_length=200, blank=True)

    category = models.ForeignKey('Category', on_delete=models.PROTECT)
    tags = models.ManyToManyField(Tag, blank=True)

    author = models.ForeignKey(User)

    def get_absolute_url(self):
        return reverse('mysite:detail', kwargs={'pk': self.pk})

    class Meta:
        ordering = ['-created_time', 'title']

    views = models.PositiveIntegerField(default=0)

    def increase_views(self):
        self.views += 1
        self.save(update_fields=['views'])

    def save(self, *args, **kwargs):
        if not self.excerpt:
            md = markdown.Markdown(extensions=[
                'markdown.extensions.extra',
                'markdown.extensions.codehilite',
            ])
            # 先将 Markdown 文本渲染成 HTML 文本
            # strip_tags 去掉 HTML 文本的全部 HTML 标签
            # 从文本摘取前 54 个字符赋给 excerpt
            self.excerpt = strip_tags(md.convert(self.body))[:54]
        # 调用父类的 save 方法将数据保存到数据库中
        super(Post, self).save(*args, **kwargs)

myproject/templates/base.html
{% load staticfiles %}
{% load mysite__tags %}
<!DOCTYPE html>
<html>
<head>
    <title>hybill's blog</title>

    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- css -->
    <!-- <link rel="stylesheet" href= "{% static 'mysite/css/bootstrap.min.css' %}"> -->
    <link href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="{% static 'mysite/css/pace.css' %}">
    <link rel="stylesheet" href="{% static 'mysite/css/custom.css' %}">
    <link rel="stylesheet" href="{% static 'mysite/css/highlights/github.css' %}">

    <!-- js -->
    <script src="{% static 'mysite/js/jquery-2.1.3.min.js' %}"></script>
    <script src="https://cdn.bootcss.com/jquery/2.1.3/jquery.min.js"></script>
    <!-- <script src="{% static 'mysite/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'mysite/js/pace.min.js' %}"></script> -->
    <script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="{% static 'mysite/js/modernizr.custom.js' %}"></script>

    <style>
        span.highlighted{
            color:red;
        }
    </style>
</head>

<body>
<div class="container">
    <header id="site-header">
        <div class="row">
            <div class="col-md-4 col-sm-5 col-xs-8">
                <div class="logo">
                    <h1><a href="{% url 'mysite:index' %}">HYBILL's Blog</a></h1>
                </div>
            </div><!-- col-md-4 -->
            <div class="col-md-8 col-sm-7 col-xs-4">
                <nav class="main-nav" role="navigation">
                    <div class="navbar-header">
                        <button type="button" id="trigger-overlay" class="navbar-toggle">
                            <span class="ion-navicon"></span>
                        </button>
                    </div>

                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="cl-effect-11"><a href="{% url 'mysite:index' %}" data-hover="Home">Home</a></li>
                            <li class="cl-effect-11"><a href="{% url 'Mine:home' %}" data-hover="Personal Page">Personal Page</a></li>
                            <!-- <li class="cl-effect-11"><a href="＃" data-hover="About">About</a></li> -->
                            <!-- <li class="cl-effect-11"><a href="contact.html" data-hover="联系">Contact</a></li> -->
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </nav>
                <div id="header-search-box">
                    <a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
                    <div id="search-form" class="search-form">
                        <form role="search" method="get" id="searchform" action="{% url 'haystack_search' %}">
                            <input type="search" name="q" placeholder="search" required>
                            <button type="submit"><span class="ion-ios-search-strong"></span></button>
                        </form>
                    </div>
                </div>
            </div><!-- col-md-8 -->
        </div>
    </header>
</div>
<!-- <div class="copyrights">Collect from <a href="http://www.cssmoban.com/">网页模板</a></div>
<div class="copyrights">Modified by <a href="http://zmrenwu.com/">追梦人物的博客</a></div> -->

<div class="content-body">
    <div class="container">
        <div class="row">
            <main class="col-md-8">
                {% block main %}
                {% endblock main %}
            </main>
            <aside class="col-md-4">
                {% block toc %}
                {% endblock toc %}
                <div class="widget widget-recent-posts">
                    <h3 class="widget-title">The Latest Content</h3>
                    {% get_recent_posts as recent_post_list %}
                    <ul>
                        {% for post in recent_post_list %}
                            <li>
                                <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                            </li>
                        {% empty %}
                            No article！
                        {% endfor %}
                    </ul>
                </div>
                <div class="widget widget-archives">
                    <h3 class="widget-title">Date</h3>
                    {% archives as date_list %}
                    <ul>
                        {% for date in date_list %}
                            <li>
                                <a href="{% url 'mysite:archives' date.year date.month %}">{{ date.year }} - {{ date.month }} </a>
                            </li>
                        {% empty %}
                            No list！
                        {% endfor %}
                    </ul>
                </div>

                <div class="widget widget-category">
                    <h3 class="widget-title">Category</h3>
                    {% get_categories as category_list %}
                    <ul>
                        {% for category in category_list %}
                            <li>
                                <a href="{% url 'mysite:category' category.pk %}">{{ category.name }} <span class="post-count">({{category.num_posts}})</span></a>
                            </li>
                        {% empty %}
                            暂无分类！
                        {% endfor %}
                    </ul>
                </div>

                <div class="widget widget-tag-cloud">
                    <h3 class="widget-title">Tags</h3>
                    {% get_tags as tag_list %}
                      <ul>
                        {% for tag in tag_list %}
                        <li>
                          <a href="{% url 'mysite:tag' tag.pk %}">{{ tag.name }}</a>
                        </li>
                        {% empty %}
                        No Tags！
                        {% endfor %}
                      </ul>
                </div>
                <div class="rss">
                    <a href="{% url 'rss' %}"><span class="ion-social-rss-outline"></span> RSS Service</a>
                </div>
            </aside>
        </div>
    </div>
</div>
<footer id="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
            </div>
        </div>
    </div>
</footer>

<!-- Mobile Menu -->
<div class="overlay overlay-hugeinc">
    <button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
    <nav>
        <ul>
            <li><a href="{% url 'mysite:index' %}">Home</a></li>
            <!-- <li><a href="full-width.html">博客</a></li> -->
            <!-- <li><a href="about.html">About</a></li>
            <li><a href="contact.html">Contact</a></li> -->
        </ul>
    </nav>
</div>

<script src="{% static 'mysite/js/script.js' %}"></script>

</body>
</html>

myproject/templates/base2.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <title>hybill's blog</title>

    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- css -->
    <!-- <link rel="stylesheet" href= "{% static 'mysite/css/bootstrap.min.css' %}"> -->
    <link href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="{% static 'mysite/css/pace.css' %}">
    <link rel="stylesheet" href="{% static 'mysite/css/custom.css' %}">
    <link rel="stylesheet" href="{% static 'mysite/css/highlights/github.css' %}">

    <!-- js -->
    <script src="{% static 'mysite/js/jquery-2.1.3.min.js' %}"></script>
    <script src="https://cdn.bootcss.com/jquery/2.1.3/jquery.min.js"></script>
    <!-- <script src="{% static 'mysite/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'mysite/js/pace.min.js' %}"></script> -->
    <script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="{% static 'mysite/js/modernizr.custom.js' %}"></script>

    <style>
        span.highlighted{
            color:red;
        }
    </style>
</head>

<body>
<div class="container">
    <header id="site-header">
        <div class="row">
            <div class="col-md-4 col-sm-5 col-xs-8">
                <div class="logo">
                    <h1><a href="{% url 'mysite:index' %}">HYBILL's Blog</a></h1>
                </div>
            </div><!-- col-md-4 -->
            <div class="col-md-8 col-sm-7 col-xs-4">
                <nav class="main-nav" role="navigation">
                    <div class="navbar-header">
                        <button type="button" id="trigger-overlay" class="navbar-toggle">
                            <span class="ion-navicon"></span>
                        </button>
                    </div>

                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="cl-effect-11"><a href="{% url 'mysite:index' %}" data-hover="Home">Home</a></li>
                            <li class="cl-effect-11"><a href="{% url 'Mine:home' %}" data-hover="Personal Page">Personal Page</a></li>
                            <!-- <li class="cl-effect-11"><a href="＃" data-hover="About">About</a></li> -->
                            <!-- <li class="cl-effect-11"><a href="contact.html" data-hover="联系">Contact</a></li> -->
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </nav>
                <div id="header-search-box">
                    <a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
                    <div id="search-form" class="search-form">
                        <form role="search" method="get" id="searchform" action="{% url 'haystack_search' %}">
                            <input type="search" name="q" placeholder="search" required>
                            <button type="submit"><span class="ion-ios-search-strong"></span></button>
                        </form>
                    </div>
                </div>
            </div><!-- col-md-8 -->
        </div>
    </header>
</div>

<div class="content-body">
    <div class="container">
        <div class="row">
            <main class="col-md-8">
                {% block main %}
                {% endblock main %}
            </main>
        </div>
    </div>
</div>