myproject/Mine/urls.py
from django.conf.urls import url
from . import views
app_name = 'Mine'
urlpatterns = [
    url(r'^Mine/$', views.IndexView.as_view(), name='home'),
    url(r'^Algorithm/$', views.AlgorithmListView.as_view(), name='Algorithm'),
]

myproject/myproject/urls.py
from django.contrib import admin
from django.conf.urls import url,include
from mysite.feeds import AllPostsRssFeed
# from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'',include('mysite.urls')),
    url(r'',include('comments.urls')),
    url(r'',include('Mine.urls')),
    url(r'^search/', include('haystack.urls')),
    url(r'^all/rss/$', AllPostsRssFeed(), name='rss'),
    # url(r'^$',views.index,name='index')
]

myproject/templates/projects/Algorithm_list.html
{% extends 'base2.html' %}
{% block main %}
{% load Mine__tags %}
<div class="container">
    <h3><a href="{% url 'Mine:Algorithm' %}" data-hover="Algorithm List">Algorithm List</a></h3>
    <div class="panel-group" id="accordion">
        {% for Algorithm in Algorithm_list %}
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4 class="panel-title">
                        <a data-toggle="collapse" data-parent="#accordion"
                           href="#collapse{{Algorithm.id}}">
                            {{Algorithm.name}}
                        </a>
                    </h4>
                </div>
                <div id="collapse{{Algorithm.id}}" class="panel-collapse collapse">
                    <div class="panel-body">
                       {{Algorithm.code|safe}}
                    </div>
                </div>
            </div>
            {% empty %}<h3>No projects</h3>
            {% endfor %}
        </div>
</div>
{% endblock main %}

myproject/templates/projects/index.html
{% extends 'base2.html' %}
{% block main %}
{% load Mine__tags %}
<div class="container">
    <h3>Basic Information:</h3>
        <p>Highest academic degree: Master of Computer Science in Syracuse University</p>
        <p>Email:hybillv5@gmail.com</p>
        <p>Recommender: Sucheta Soundarajan (my professor) - http://www.soundarajan.org/</p>
        <p>Hobbies: Go(a chess game), traveling</p>
    <h3>Skills:</h3>
    <ul>
        <li>IOS development</li>
        <li>Python development : Django, Web Crawler, Data mining</li>
        <li>Strong data structure and algorithm skills</li>
        <li>Neural Network</li>
        <li>Recommend system</li>
    </ul>
    <h3>Tools:</h3>
    <ul>
        <li>Xcode</li>
        <li>PyCharm</li>
        <li>Git,Source Tree</li>
        <li>Command line in Linux</li>
        <li>Mysql, SqlSever</li>
    </ul>
    <h3>Projects List:</h3>
    <div class="panel-group" id="accordion">
        {% for project in Projects_list %}
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4 class="panel-title">
                        <a data-toggle="collapse" data-parent="#accordion"
                           href="#collapse{{project.id}}">
                            {{project.create_time}} -- {{project.name}}
                        </a>
                    </h4>
                </div>
                <div id="collapse{{project.id}}" class="panel-collapse collapse">
                    <div class="panel-body">
                        <h4><strong>Description:</strong></h4>
                          <p>{{project.description}}</p>
                           <div class="widget widget-tag-cloud">
                               <h4><strong>Programming Language:</strong></h4>
                               <ul>
                                   {% for tag in project.programming_language.all %}
                                   <li>{{ tag.name}}</li>
                                   {% empty %} Empty
                                   {% endfor %}
                               </ul>
                            </div>
                        <div class="widget widget-tag-cloud">
                               <h4><strong>Tech Stack:</strong></h4>
                               <ul>
                                   {% for tag in project.tech_stack.all %}
                                   <li>{{ tag.name}}</li>
                                   {% empty %} Empty
                                   {% endfor %}
                               </ul>
                            </div>
                       <div class="widget widget-tag-cloud">
                               <h4><strong>Development Tools:</strong></h4>
                               <ul>
                                   {% for tag in project.development_tools.all %}
                                   <li>{{ tag.name}}</li>
                                   {% empty %} Empty
                                   {% endfor %}
                               </ul>
                            </div>
                      <h4><strong>Details:</strong></h4>
                          <p>{{project.details}}</p>
                    </div>
                </div>
            </div>
            {% empty %}<h3>No projects</h3>
            {% endfor %}
        </div>
        <h3><a style="color:#0455df;" href="{% url 'Mine:Algorithm' %}">Algorithm List >> </a></h3>
</div>
{% endblock main %}